import sys

latexopt = """
            -shell-escape 
            -interaction nonstopmode 
            -file-line-error 
            -halt-on-error
            """

docs_path = "../docs/"

with open(f"{docs_path}Makefile", "r") as file:
    lines = file.readlines()

output_name = lines[0].strip('\n').replace(' ', '').split('=')[-1]

#============================RULES================================
rule targets:
    input:
        thesis = f"{docs_path}{output_name}.pdf",
        dag = "dag.png",

rule collect_figures:
    input:
        social_max_plot = "../docs/figures/social_max.pgf",
        elasticity_plot = "../docs/figures/elasticity.pgf"
    output:
        log = "figure-log.txt"
    shell:
        f"""
        echo {input} > figure-log.txt
        """

if sys.platform == 'Windows':
    rule build_thesis:
        input: 
            main_tex = f"{docs_path}{output_name}.tex",
            log = "figure-log.txt"
        output: f"{docs_path}{output_name}.pdf"
        shell:
            f"""
            cd ../docs && \
            pdflatex {latexopt} {output_name}.tex && \
            biber {output_name} && \
            pdflatex {latexopt} {output_name}.tex && \
            pdflatex {latexopt} {output_name}.tex &&
            """
elif sys.platform in ['darwin', 'linux']:
    rule build_thesis:
        input: 
            main_tex = f"{docs_path}{output_name}.tex",
            log = "figure-log.txt"
        output: f"{docs_path}{output_name}.pdf"
        shell:
            f"""
            (cd {docs_path} && make)
            """

rule build_dag:
    input: "Snakefile"
    output:
        "dag.png"
    shell:
        "snakemake --dag | dot -Tpng > {output}"


rule plot_social_welfare_max:
    input: "scripts/social_welfare_maximization.py"
    output: 
        social_max_plot = "../docs/figures/social_max.pgf",
        elasticity_plot = "../docs/figures/elasticity.pgf"
    script: ""